### ISSUE TITLE
Adding a working 'Confirm password' option in the Sign up page

### ISSUE THREAD

**Issue by aditi13y** [kom-senapati/bot-verse#101]
In the sign up page , a confirm password option can be added so that the user can double check the password they have entered. 
I want to add a confirm password which will match the password with the password above.
It will throw an error if the passwords dont match.

**Comment by aditi13y** [comment]
I am a gssoc ext and hactoberfest contributor.

**Comment by kom-senapati** [comment]
Ok add it

**Comment by ARP-WorkerHack1** [comment]
I would like to work on this. Pl assign me this.

**Comment by ARP-WorkerHack1** [comment]
I am also a gssoc ext and hactoberfest contributor.

**Comment by kom-senapati** [comment]
@ARP-WorkerHack1 This issue is taken, find another or raise one

**Comment by kom-senapati** [comment]
@aditi13y Are you working ?

**Comment by aditi13y** [comment]
Yes, I will get it done by tomorrow.

**Comment by kom-senapati** [comment]
Any updates ??

**Comment by aditi13y** [comment]
Due to some unforeseen circumstances, I was busy last week, I have completed the half of it  I will put a pr by tomorrow.

**Comment by nandini-queen-of-my-world** [comment]
assign this to me

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on it I will add in React

**Comment by kom-senapati** [comment]
Yup you can do
