### ISSUE TITLE
Feature: Add Eye Icon Functionality for Password Field in Sign-Up/ Sign-In Form

### ISSUE THREAD

**Issue by Ayushjhawar8** [kom-senapati/bot-verse#106]
### Description
Add functionality to show/hide the password in the sign-up form using an eye icon.

### Proposed Changes
- Add an eye icon to the password input field.
- Position the icon at the middle right of the input field.
- Implement JavaScript for toggling password visibility.

### Steps to Reproduce
1. Open the sign-up form.
2. Notice the absence of password visibility toggle.

### Expected Outcome
- Eye icon appears in the password field.
- Clicking the icon toggles password visibility.

**Comment by Ayushjhawar8** [comment]
please assign me =)

**Comment by kom-senapati** [comment]
Ok add this
