### ISSUE TITLE
Adding McDonald's Ordering chatbot

### ISSUE THREAD

**Issue by Amanjayswal500** [kom-senapati/bot-verse#115]
Problem Statement:
Create a McDonald's ordering chatbot that streamlines the customer ordering process by automating menu selection, customization.

Solution Proposal:
Develop a conversational AI chatbot using NLP and machine learning to enable customers to browse the menu, customize orders,  ensuring fast and user-friendly interaction across multiple platforms.

Output screen and conversesion
![Screenshot 2024-10-10 103756](https://github.com/user-attachments/assets/562eedc0-1fce-438b-bac8-b1ab10928a57)

**Comment by Amanjayswal500** [comment]
@kom-senapati 

Please add the following tags to the issue: gssoc-ext, hacktoberfest.
Kindly assign this issue to @Amanjayswal500

**Comment by kom-senapati** [comment]
@Amanjayswal500 Please see whats the project about, we just need 10 system chatbots and more bots will be created by users.
