### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]:  Add a FAQ's Page 

### ISSUE THREAD

**Issue by vanshikag1410** [kom-senapati/bot-verse#134]
I would like to add a FAQ's page to this project which would be kinda user friendly.

**Comment by kom-senapati** [comment]
It is necessary to complete the entire issue template correctly; why did you submit only a single line?

**Comment by kom-senapati** [comment]
Yep, you can add that in app/templates/index.html.

**Comment by kom-senapati** [comment]
Any updates @vanshikag1410

**Comment by vanshikag1410** [comment]
> Any updates @vanshikag1410

I'm working on it. Would update the page layout soon.

**Comment by kom-senapati** [comment]
Share the design you are working upon

**Comment by kom-senapati** [comment]
No updates so unassigning @vanshikag1410

**Comment by nandini-queen-of-my-world** [comment]
assign this to me

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this issue

**Comment by kom-senapati** [comment]
@priyanshuverma-dev go ahead

**Comment by kom-senapati** [comment]
I am making this level2, add some animation as well
