### ISSUE TITLE
🐛 [BUG]: likes and reports columns missing from chatbots table

### ISSUE THREAD

**Issue by parteekxo** [kom-senapati/bot-verse#135]
### Description
The chatbots table is missing the likes and reports columns, causing an error when attempting to query the table. This occurs when the application tries to retrieve chatbot data that includes these fields. Without these columns, the database cannot process certain queries, leading to an OperationalError.

### Approach
To resolve this, we will modify the database schema to include the missing likes and reports columns. These columns should be added with appropriate data types (e.g., integer for likes and reports) using a migration script to update the database.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/8727f0ff-f804-4076-bc89-d2d20b8ad567)

### Proposed Changes
Create a database migration to add likes and reports columns to the chatbots table.
Update the application to handle these new fields appropriately.
Verify that the schema matches the expected design, and test to ensure that the errors are resolved.

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Akashdeep Singh
- Email: parteek.xo.3@gmail.com
- GitHub Link: https://github.com/parteekxo
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
I am a Contributor, GSSOC-EXT and Hacktoberfest.
***********************************************************************

### Checklist
- [x] I have included a clear and detailed description.
- [x] I have provided necessary logs, screenshots, or other files.
- [x] I have described the expected vs actual behavior.
- [x] I have mentioned related issues or pull requests if any.

***********************************************************************

**Comment by kom-senapati** [comment]
Likes and reports columns exist in that model.

**Comment by parteekxo** [comment]
> Likes and reports columns exist in that model.

but it isnt working and the live site is down too
