### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: Add better error messages

### ISSUE THREAD

**Issue by shivenyadavs** [kom-senapati/bot-verse#138]
### Approach to Creating This Feature

To implement this feature, I will:

Review the existing error handling in the build_css function of the script.
Replace generic error messages with more descriptive ones, detailing the specific issue.
Include suggestions or steps that users can take to resolve these issues, improving the overall user experience.
Ensure that any changes are consistent with the existing code style.

### Screenshots 📷

N/A

### Features Expected

Currently, the error messages displayed in the CSS building script are minimal and can lead to confusion for users. This enhancement aims to provide more informative and user-friendly error messages. For example, if the input CSS file is not found or if the Tailwind CLI is not executable, the error messages will explicitly state the issue and offer suggestions for resolution.

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: shiven yadav s
- Email:shivenyadavs@gmail.com
- GitHub Link:https://github.com/shivenyadavs?tab=repositories
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [ ] I have provided any relevant documentation or references.
- [ ] I have included screenshots or examples where applicable.
- [x] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kom-senapati** [comment]
I dont think we need this
