### ISSUE TITLE
UI: New Landing Page & Viewport

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#14]
- design landing page for modern world
- Glimpse of that are;
- fix viewport on mobile screen

https://www.loom.com/share/b5adfe22e988490093f3ac3e38011011?sid=95464019-1639-4cfc-87cb-0946242af33c

**Comment by priyanshuverma-dev** [comment]
May I solve this issue 😄

**Comment by priyanshuverma-dev** [comment]
I have changes ready if design suits you then Let me pull the PR @kom-senapati

**Comment by kom-senapati** [comment]
Ok make the PR
