### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: Bot and Image of the day and a welcome message

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#140]
### Description
- add bot of the day
- add image of the day
- add a welcome message on dashboard

### Features Expected

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Priyanshu Verma
- Email: priyanshuverma@outlook.in
- GitHub Link: https://github.com/priyanshuverma-dev
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC

***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [ ] I have provided any relevant documentation or references.
- [ ] I have included screenshots or examples where applicable.
- [x] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kom-senapati** [comment]
Do handle when no images are there, for the bot you can do a system bot even if any user didn't create any!
