### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: A Coding LLM Chatbot extension for VS Code 

### ISSUE THREAD

**Issue by Panchadip-128** [kom-senapati/bot-verse#144]
### Description
This extension was developed to enhance coding efficiency by integrating advanced language models like Llama 3.1, OpenAI’s GPT-3.5-turbo, and Gemini 1.5. These models offer powerful code generation, suggestion capabilities, and the ability to solve complex coding problems. The extension is designed with a user-friendly interface and can be easily integrated into your existing workflow.

### Approach to Creating This Feature
Before using this extension, we need to ensure that we have the following installed on our system: ➢ Visual Studio Code (version 1.92.0 or higher) ➢ Node.js (for running the extension) ➢ TypeScript (for compiling TypeScript files) Additionally, we need to make sure that we have access to API keys from Together.ai, Groq, OpenAI, or other supported providers to interact with the language models. Thereafter we built the linked features,customize backend and front end functionalities, LLM engines and build requisite extension

### Screenshots 📷
![copilot1](https://github.com/user-attachments/assets/fa13d395-cc86-4839-95aa-1002c264eb9d)
![copilot2](https://github.com/user-attachments/assets/2dd7328e-9779-4868-bd8f-79bb24b7981e)

### Features Expected
➢ Model Integration: Supports switching between Llama 3.1, GPT-3.5-turbo, and Gemini models. ➢ Code Generation: Generates code snippets, solves LeetCode & DSA problems, and supports autocompletion ➢ User-Friendly Interface: Simplified design for ease of use, allowing users to interact with the AI seamlessly

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Panchadip Bhattacharjee
- Email:panchadip128@gmail.com
- GitHub Link: https://github.com/Panchadip-128
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSoC Extdv 2024 Contributor
***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [x] I have provided any relevant documentation or references.
- [x] I have included screenshots or examples where applicable.
- [ ] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Panchadip-128** [comment]
@kom-senapati Please review once and if possible assign me this project under suitable labels, its interesting, unique and powerful with Gemini 1.5, ChatGPT 3.5 turbo engines and Llama 3.1 LLM engines for power-packed coding suggestions, code generation and efficient debugging and a lot more for general use cases as well

**Comment by kom-senapati** [comment]
This project is cool but outside the scope of our project.
