### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: Add a Remember me checkbox in the login page 

### ISSUE THREAD

**Issue by vanshikag1410** [kom-senapati/bot-verse#145]
Adding a checkbox of "Remember me" will be user friendly as they will not have to mention their credentials again n again.

I would like to work on this so kindly assign this issue to me.

- Vanshika Gupta 
- vanshikagupta1404@gmail.com
- GSSOC

**Comment by kom-senapati** [comment]
This is good one

**Comment by kom-senapati** [comment]
go ahead

**Comment by nandini-queen-of-my-world** [comment]
Assign this to me
