### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: React Client Setup

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#148]
### Description

Project setup separate client and server setup react app

### Approach to Creating This Feature

- Separate react client and flask server in `client`,`server` folders
- setup VITE react app inside `client` folder
- setup router and routes for current project (complex)
- setup pages for all route only demo

### Features Expected

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Priyanshu Verma
- Email: priyanshuverma@outlook.in
- GitHub Link: https://github.com/priyanshuverma-dev
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
  - GSSOC
***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [ ] I have provided any relevant documentation or references.
- [ ] I have included screenshots or examples where applicable.
- [ ] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this issue

**Comment by kom-senapati** [comment]
For now, do in a separate directory called client
