### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: Custom themes

### ISSUE THREAD

**Issue by yashksaini-coder** [kom-senapati/bot-verse#150]
### Description
Let users personalize the app interface with different themes.

### Features Expected

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Yash K. Saini
- Email: ys3853428@gmail.com
- GitHub Link: [yashksaini-coder](https://github.com/yashksaini-coder)
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSoC

***********************************************************************

### Checklist
- [X] I have included a clear and detailed description of the enhancement.
- [X] I have provided any relevant documentation or references.
- [X] I have included screenshots or examples where applicable.
- [X] I have mentioned related issues or pull requests if any.X
***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by yashksaini-coder** [comment]
@kom-senapati can you assign this issue to me

**Comment by kom-senapati** [comment]
Yes you can do this add 4-5 different themes except dark, light

**Comment by yashksaini-coder** [comment]
bro I can't fix this issue so I am unassigning myself, I tried using this [multi-theme](https://github.com/estevanmaito/tailwindcss-multi-theme) package to toggle between multiple themes, 

Hope this helps

**Comment by priyanshuverma-dev** [comment]
May I work on this issue @kom-senapati
