### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]: Design Landing page for React 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#152]
### Description

Make a new Landing Page for React client
### Features Expected

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: Priyanshu Verma
- Email: 
- GitHub Link:
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [ ] I have provided any relevant documentation or references.
- [ ] I have included screenshots or examples where applicable.
- [ ] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kom-senapati** [comment]
No need of new pages just migrate old pages with styles in react!
Do for 2-3 pages in one issue
