### ISSUE TITLE
🧑‍💻 [ENHANCEMENT]:  Automated project structure updation using github workflows, python scripts and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [kom-senapati/bot-verse#154]
### Description
Automated project structure updation using github workflows, python scripts and action bot

### Approach to Creating This Feature
Add worflow in .github and add required script inside .github and integrate with action bot

### Screenshots 📷
![image](https://github.com/user-attachments/assets/26bbda18-4082-4d17-8222-1488fbcdb3fb)

### Features Expected
Automated project structure updation

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue:**
- Full name: J B Mugundh
- Email: mugundhjb@gmail.com
- GitHub Link: https://github.com/J-B-Mugundh
- What is your participant role? GSSOC-EXTD

***********************************************************************

### Checklist
- [x] I have included a clear and detailed description of the enhancement.
- [x] I have provided any relevant documentation or references.
- [x] I have included screenshots or examples where applicable.
- [x] I have mentioned related issues or pull requests if any.

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kom-senapati** [comment]
We don't need that right now
