### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [kom-senapati/bot-verse#155]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @kom-senapati 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by kom-senapati** [comment]
Its already implemented. Also, your PR checker didn't work on some PRs so deleted it!
