### ISSUE TITLE
🚀 Feature: Dashboard Page and Create/Delete Chatbot 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#159]
### 🔖 Feature description

- dashboard Page
- create chatbot
- delete chatbot
- update chatbot

### 🎤 Why is this feature needed ?

Needed for react client

### ✌️ How do you aim to achieve this?

using react

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Go ahead!
