### ISSUE TITLE
🚀 Feature: Migrate Profile Page and Settings Page

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#160]
### 🔖 Feature description

- migrate profile page
- migrate settings page

### 🎤 Why is this feature needed ?

react migration

### ✌️ How do you aim to achieve this?

react

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
I like your progress!
