### ISSUE TITLE
🚀 Feature: Chatting Page and Hub with remaining tweaks

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#165]
### 🔖 Feature description

- chatting page
- hub page
- more fixes and migrations

### 🎤 Why is this feature needed ?

React Migration

### ✌️ How do you aim to achieve this?

React

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Go ahead
