### ISSUE TITLE
🚀 Feature: Migration of remaining pages and features

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#166]
### 🔖 Feature description

It will be final migration remove depreciated `API` functions and
Make it seem-less to use without any major issue damage.  

### 🎤 Why is this feature needed ?

Enable all features

### ✌️ How do you aim to achieve this?

LAST React Migrations

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok cool
