### ISSUE TITLE
🚀 Feature: Add a copilot assistant

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#169]
### 🔖 Feature description

Add a personal assistant.

### 🎤 Why is this feature needed ?

For better user experience

### ✌️ How do you aim to achieve this?

Using copilot

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Yes do this
