### ISSUE TITLE
🚀 Feature: Migrate speech recognition and speech synthesis pages

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#172]
### 🔖 Feature description

- Migrate speech recognition and synth Pages

### 🎤 Why is this feature needed ?

React migration

### ✌️ How do you aim to achieve this?

React files

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
@priyanshuverma-dev Can you confirm if these pages are not migrated

**Comment by priyanshuverma-dev** [comment]
@kom-senapati All pages are migrated

**Comment by priyanshuverma-dev** [comment]
Some Features are remaining only like speech recog. and speech systh.

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : okay, I updated the title

**Comment by kom-senapati** [comment]
Ok you can do that

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : faced some issues related to flask setup. Today, I will push code changes

**Comment by kom-senapati** [comment]
You can ask in discord about setup
