### ISSUE TITLE
🚀 Feature: Migrate update and create chatbot pages

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#173]
### 🔖 Feature description

Migrate Update and Create chatbot pages

### 🎤 Why is this feature needed ?

React Migration

### ✌️ How do you aim to achieve this?

React

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
This is done I think as dialogs
