### ISSUE TITLE
🚀 Feature: Settings Page and code quality update

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#176]
### 🔖 Feature description

- Add settings page like previous
- Code refactor remove unused `API` routes
- Performance enhancement as of now everything is fetched from server even static things and their is not optimization
- Add Optimistic UI updates 
- *This won't touch templates as some issues are on that*
- *I will only update `client`*

### 🎤 Why is this feature needed ?

- Because of performance issues and bugs

### ✌️ How do you aim to achieve this?

Code refactor

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
go ahead
