### ISSUE TITLE
🚀 Feature: Profile Like and Contribution Count

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#178]
### 🔖 Feature description

- Add a feature to like user profile
- Add a share button
- Contribution count system
- If user publish `1 BOT == 5 POINTS`
- If user publish `1 IMAGE == 1 POINTS`

### 🎤 Why is this feature needed ?

Engagement

### ✌️ How do you aim to achieve this?

Adding new logic

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Cool idea
