### ISSUE TITLE
🚀 Feature: Add loading Skeletons 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#179]
### 🔖 Feature description

- On every loading add skeleton for better UI experience

### 🎤 Why is this feature needed ?

Better UI/UX

### ✌️ How do you aim to achieve this?

UI framework

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok do it
