### ISSUE TITLE
🚀 Feature: ADD Mutlilanguage support 

### ISSUE THREAD

**Issue by shubhagarwal1** [kom-senapati/bot-verse#184]
### 🔖 Feature description

supports multiple languages

### 🎤 Why is this feature needed ?

So that Apllication could be user by Diversity of users

### ✌️ How do you aim to achieve this?

adding script that will support multiple languages

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
Could you tell me your approach for this feature?

**Comment by shubhagarwal1** [comment]
> Could you tell me your approach for this feature?

Hey @kom-senapati, sure we will intergrate a language model which will basically change the text of the website according to the selected language

**Comment by kom-senapati** [comment]
Nah I would like a manual setup for some common languages like eng, hindi, spanish, etc. Use i18n react

**Comment by kom-senapati** [comment]
Yup go ahead
