### ISSUE TITLE
🚀 Feature: ADD CICD GITHUB WORKFLOWS

### ISSUE THREAD

**Issue by shubhagarwal1** [kom-senapati/bot-verse#185]
### 🔖 Feature description

Workflow to be implemeted

Auto Comment on Issue
Auto Comment on PR
Auto Comment on PR Merge
Auto Label Issue
Auto Label Issues
Auto Label PRs
Close Issues on PR Merge
Close Old Issues
Close Stale PRs
Comment on Issue Close

### 🎤 Why is this feature needed ?

To automate the repeating tasks

### ✌️ How do you aim to achieve this?

add yml files

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
Firstly, review the existing workflows and issue/PR templates.

I would like 'enhancement' and 'bug' labels, as well as comments, to be added whenever an issue/PR is opened. Please do not set up any actions for closing issues or PRs.

Consider adding a workflow that posts a message asking for updates if someone has been inactive on an issue for 3 days, and if there is no response by the 5th day, remove the assignment and label it as 'up for grabs'.

Implement another workflow to update the contributors list in the README with every commit, encapsulated within detail-summary HTML tags.
