### ISSUE TITLE
Add issues & PR templates

### ISSUE THREAD

**Issue by yashksaini-coder** [kom-senapati/bot-verse#19]
Hi, @kom-senapati your project could use templates for issues & PR requests. Enhance it more xD.

**Comment by kom-senapati** [comment]
I have sent in discord to do this. No contributors joining discord. Also you can join it and tell there :)

**Comment by kom-senapati** [comment]
Let's see who want to do this

**Comment by yashksaini-coder** [comment]
> Let's see who want to do this

join where in discord can you tell me @kom-senapati

**Comment by kom-senapati** [comment]
Its in the readme and contributing.md as well

**Comment by sumana-2705** [comment]
I want to work on this issue, can you please assign it to me @kom-senapati

**Comment by kom-senapati** [comment]
I think @yashksaini-coder messaged me for doing this issue. So I am assigning him. You can do other contributions maybe adding a backend guide that will help devs to understand backend.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by yashksaini-coder** [comment]
@kom-senapati I have raised a PR #46 that fixes this issue.
