### ISSUE TITLE
🚀 Feature: update readme

### ISSUE THREAD

**Issue by agarwalbhargavi** [kom-senapati/bot-verse#190]
### 🔖 Feature description

would like to add gssoc hacktoberfest banner...also live tracking of contributors forkers ,stargrazers, pull requests, commits ,and issues

### 🎤 Why is this feature needed ?

it will enhance the readme file

### ✌️ How do you aim to achieve this?

by adding such features in readme file

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

@kom-senapati kindly assign me this issue

**Comment by kom-senapati** [comment]
No need
