### ISSUE TITLE
🚀 Feature: Adding Social Media icons to Follow us

### ISSUE THREAD

**Issue by siri-chandana-macha** [kom-senapati/bot-verse#191]
### 🔖 Feature description

Add icons for popular social media platforms to the app's interface, linking users directly to social media profiles. Icons should be clearly visible in the footer.

### 🎤 Why is this feature needed ?

This will make it easier for users to follow our social media, stay updated, and engage with our content. It promotes user retention and strengthens community connection.

### ✌️ How do you aim to achieve this?

Integrate social media icons (GitHub,Twitter, LinkedIn, Facebook, etc.) styled to match the app’s theme, each linking to our profiles. 

### 🔄️ Additional Information

@kom-senapati please issue this under gssoc-extd, hacktoberfest-accepted and level2

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Okay, please add my social media links in the footer, but only on the landing page.

**Comment by siri-chandana-macha** [comment]
ok

**Comment by kom-senapati** [comment]
Any updates ?

**Comment by kom-senapati** [comment]
Unassigning as no updates

**Comment by nandini-queen-of-my-world** [comment]
Assign this to me

**Comment by kom-senapati** [comment]
Any updates?

**Comment by priyanshuverma-dev** [comment]
@kom-senapati may I work on this issue 
Will add twitter, linkedin and github profiles in footer

**Comment by kom-senapati** [comment]
yes
