### ISSUE TITLE
🚀 Feature: Leaderboard for contribution score

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#193]
### 🔖 Feature description

- add a leaderboard Page by the basis of contribution score.

### 🎤 Why is this feature needed ?

For more engagement

### ✌️ How do you aim to achieve this?

A new Page and fetching routes

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Good idea
