### ISSUE TITLE
🚀 Feature: Option to add API key by user

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#194]
### 🔖 Feature description

A option to add API key for AI engine

### 🎤 Why is this feature needed ?

For sake of being environment we need this issue so that we can operate our project efficiently

### ✌️ How do you aim to achieve this?

adding new settings option

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Implement a feature in the client that restricts bot access unless an API key is added in the settings.
