### ISSUE TITLE
🚀 Feature: More AI engine to use

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#195]
### 🔖 Feature description

There should be variety in AI engine to use.
like OPENAI, GROQ, GEMINI

### 🎤 Why is this feature needed ?

Better AI performance

### ✌️ How do you aim to achieve this?

Adding more AI engines

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Submit a PR then I will assign you this, lets see if anyone else want to work on this

**Comment by kom-senapati** [comment]
You can proceed
