### ISSUE TITLE
Enhancing a Flask Chatbot Application: Code Review and Best Practices - routes.py

### ISSUE THREAD

**Issue by Deeptig9138** [kom-senapati/bot-verse#2]
Unused Imports: The import from crypt import methods is not used in the code. This should be removed to clean up the code.
Error Handling: Consider adding more comprehensive error handling, especially in database operations
User Feedback: Flash messages for actions like creating and updating chatbots are missing, which could improve user experience.
Security: Ensure all user inputs are validated and sanitized to prevent SQL injection and XSS attacks.
Route Decorators: The route decorators could include more HTTP methods for better RESTful practices (e.g., using PATCH for updates).
Code Duplication: The checks for chatbot.user_id != current_user.uid are repeated in several places. This logic could be abstracted into a helper function.
Response Handling: When getting a response from the chat_with_chatbot function, handle potential failures gracefully to avoid breaking the flow.
Redirect after POST: After certain POST requests, ensure the user is redirected appropriately to avoid double submissions.

Can you please assign this to me @kom-senapati

**Comment by kom-senapati** [comment]
There are so many issues here. Create an issue for one bug or feature only.

**Comment by Deeptig9138** [comment]
> There are so many issues here. Create an issue for one bug or feature only.

Would you like to assign any one bug/feature to me? Or if it was for me to choose i would like to work on the security aspects of it
