### ISSUE TITLE
🚀 Feature: Comment Section for Chatbots

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#203]
### 🔖 Feature description

- A commenting section for chatbots

### 🎤 Why is this feature needed ?

For corrections of chatbots

### ✌️ How do you aim to achieve this?

Adding a comment form

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok do it
