### ISSUE TITLE
🐛 Bug Report: Authentication 422 Error on data fetching

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#209]
### 📜 Description

when login user explicitly needs to refresh page 

### 👟 Reproduction steps

1. Login 
2. on dashboard see error

### 👍 Expected behavior

On errors

### 👎 Actual Behavior with Screenshots

![error](https://github.com/user-attachments/assets/3ce92c3b-508e-4f7a-b44f-892b941d7895)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kom-senapati** [comment]
Ok solve this bug
