### ISSUE TITLE
🚀 Feature: Add settings button on Chatting Page and Chatbot View button

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#213]
### 🔖 Feature description

- Make settings accessible on chatting page
- Make a redirect to chatbot view page on clicking on name of chatbot 

### 🎤 Why is this feature needed ?

For more accessible of features

### ✌️ How do you aim to achieve this?

adding feature to do so

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Good issue
