### ISSUE TITLE
🚀 Feature: Magic Tools to use with Chatbot

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#215]
### 🔖 Feature description

- tool like generate a audio file from text and download text as `.txt` form.

### 🎤 Why is this feature needed ?

New Feature

### ✌️ How do you aim to achieve this?

Using browsers API

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Yeah awesome ideas!
