### ISSUE TITLE
🚀 Feature: Magic to translate text to different languages 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#219]
### 🔖 Feature description

A magic tool to translate text to different language

### 🎤 Why is this feature needed ?

To distinct users

### ✌️ How do you aim to achieve this?

using free python lib

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Good idea
