### ISSUE TITLE
🚀 Feature: Search Functionality and Chatbot Catrgories

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#222]
### 🔖 Feature description

Add a filter on HUB and search bar

### 🎤 Why is this feature needed ?

For better accessibility

### ✌️ How do you aim to achieve this?

1. Need to limit add category option to schema
2. update create chatbot and update chatbot APIs and UI
3. add filter on HUB page
4. Do logic checking rendering and more

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
ok good feature
