### ISSUE TITLE
🚀 Feature: Add Templates Option when creating chatbot

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#223]
### 🔖 Feature description

Add Templates Option when creating chatbot so user will not have blank canvas

### 🎤 Why is this feature needed ?

user will not have blank canvas to start with

### ✌️ How do you aim to achieve this?

adding templates like customer support, Q&A, etc

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
can add this
