### ISSUE TITLE
🚀 Feature: "Greetings" workflow for PRs

### ISSUE THREAD

**Issue by samyak-aditya** [kom-senapati/bot-verse#224]
### 🔖 Feature description

**Description:**
This pull request introduces a "Greetings" workflow, designed to automatically send a warm, customized welcome to users who open new pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: New contributors receive instant, personalized messages that acknowledge their efforts:
  - **For Pull Requests**: "🎉 Hi @${{ github.actor }}! Thank you for your pull request—your work brings us closer to our goals! A maintainer will review your submission shortly. We’re grateful for your effort and commitment."

This addition enhances contributor engagement by making the repository more welcoming and responsive to new participants.

### 🎤 Why is this feature needed ?

**Implementation Details:**
- Added a workflow file, `greetings.yml`, in the `.github/workflows` directory.
- Configured the workflow to trigger on both new issues and pull requests.
- Leveraged the `actions/first-interaction` action to handle customized greeting messages.

### ✌️ How do you aim to achieve this?

**Key Features:**
- **Automatic Greeting**: New contributors receive instant, personalized messages that acknowledge their efforts:
  - **For Pull Requests**: "🎉 Hi @${{ github.actor }}! Thank you for your pull request—your work brings us closer to our goals! A maintainer will review your submission shortly. We’re grateful for your effort and commitment."

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

> Yes I am willing to submit a PR!
Its now available for other contributors

**Comment by kom-senapati** [comment]
You can do for pr one

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this issue.
I will add following:
- PR Raise message `pr_raise.yaml`
- PR merge message `pr_merge.yaml`

**Comment by kom-senapati** [comment]
You can add @priyanshuverma-dev
