### ISSUE TITLE
🚀 Feature: Github Workflow : Notify Contributors When Pull Requests Are Merged

### ISSUE THREAD

**Issue by samyak-aditya** [kom-senapati/bot-verse#225]
### 🔖 Feature description

**Background:**
Currently, when a pull request (PR) is merged, contributors are not notified about the status of their contributions. It’s important to acknowledge their efforts and keep them informed to foster a positive and collaborative environment.

### It should be implemented because

**Benefits:**
- Enhances contributor engagement.
- Acknowledges their work, which can encourage future contributions.
- Improves communication within the project.

### ✌️ How do you aim to achieve this?

Implementation Details:

Added a workflow file, in the .github/workflows directory.
Configured the workflow to trigger on both new issues and pull requests.
Leveraged the actions/first-interaction action to handle customized greeting messages.

hey @kom-senapati Please assign me this Task

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
No need of this
