### ISSUE TITLE
🚀 Feature: Improve Welcome page of the Application

### ISSUE THREAD

**Issue by shubhagarwal1** [kom-senapati/bot-verse#226]
### 🔖 Feature description

I will improve the welcome page of the application as of now it is simple and not much css is used

### 🎤 Why is this feature needed ?

to make the application more appealing and better user exp.

### ✌️ How do you aim to achieve this?

i will achieve this by using some stying techniques and making it look good

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
Tailwind css is used!
Explain me in detail what you want to do

**Comment by shubhagarwal1** [comment]
> Tailwind css is used! Explain me in detail what you want to do

I will keep the existing theme of the application,
changes i will do 
revamp the cards add some appealing look to them, add some more moderl components like will use accordian, slider, hoverchanges and rest of the things that align the page. 
like for now our site has simplicity, i will try to make it more appelaing with existing theme and designed followed

will try to make the data more corretly placed whihc helps user to  navigate the welcome screen properly and so it would be better user exp.

**Comment by shubhagarwal1** [comment]
![Screenshot 2024-10-31 at 8 34 23 AM](http 
s://github.com/user-attachments/assets/327af0a9-33e2-4a4c-bac3-22b9ee9ed9d8)
for now dashboard is like this, so i will try to add some colors, some more text decorations and things like that

**Comment by kom-senapati** [comment]
Ok can do

**Comment by kom-senapati** [comment]
Any updates?

**Comment by kom-senapati** [comment]
I will close this issue if no updates
