### ISSUE TITLE
🚀 Feature: Enhance the Leaderboard design 

### ISSUE THREAD

**Issue by shubhagarwal1** [kom-senapati/bot-verse#227]
### 🔖 Feature description

to make the desing more connecting to the application

### 🎤 Why is this feature needed ?

to enhae user exp.

### ✌️ How do you aim to achieve this?

i am plaing to change the structure of the code, and make it more connecting to the content on the page,
the content on the page should be well organised and kept well

changes to be made 
- change the position of Open Command Panel

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
Ok you can work on this
