### ISSUE TITLE
🚀 Feature: Add delete button to remove user created bots

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#229]
### 🔖 Feature description

Add delete button to remove user created bots

### 🎤 Why is this feature needed ?

- There is no option to remove bots once created.

### ✌️ How do you aim to achieve this?

- Add delete icon and remove bot when clicked

### 🔄️ Additional Information

![c1](https://github.com/user-attachments/assets/a2bae57a-2f00-42b5-929e-23639a7d1436)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Add it
