### ISSUE TITLE
Enhance Navbar and Add Logout Icon

### ISSUE THREAD

**Issue by Varsha-1605** [kom-senapati/bot-verse#23]
# Expected Update:
1.  Add a gradient background and shadow to the navbar.
2.  Add smooth hover transitions to navbar links.
3.  Include a logout icon next to the "Logout" text.
4.  Ensure consistency across all relevant pages.

**Comment by kom-senapati** [comment]
Share a design you want to implement

**Comment by Varsha-1605** [comment]
sure along with the dark mode toggle!

![image](https://github.com/user-attachments/assets/f7a3989b-915c-447b-87a3-59fc44638a8c)

**Comment by Varsha-1605** [comment]
may i go ahead?

**Comment by kom-senapati** [comment]
Complete assigned tasks

**Comment by kom-senapati** [comment]
Ok I am assigning this now
