### ISSUE TITLE
🚀 Feature: Add emoji support in chat box

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#230]
### 🔖 Feature description

 Allow users to use emojis in the chat box

### 🎤 Why is this feature needed ?

to make interactions more engaging.

### ✌️ How do you aim to achieve this?

Add emoji component

### 🔄️ Additional Information

![em1](https://github.com/user-attachments/assets/11f2df94-eadb-48e7-b957-4fa3c517c09c)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
This is good feature
