### ISSUE TITLE
🚀 Feature: Live Demo

### ISSUE THREAD

**Issue by ArnavK-09** [kom-senapati/bot-verse#233]
### 🔖 Feature description

Deploy on any platform and present live demo

### 🎤 Why is this feature needed ?

cos i dont have self to use python

### ✌️ How do you aim to achieve this?

ifykyk

### 🔄️ Additional Information

i tried on one platform & workd

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kom-senapati** [comment]
No need for now
