### ISSUE TITLE
🚀 Feature: Add Chatbot Version Control

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#236]
### 🔖 Feature description

Version control for chatbot prompt

### 🎤 Why is this feature needed ?

For better prompt management

### ✌️ How do you aim to achieve this?

Using A new table

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok solve it
