### ISSUE TITLE
🐛 Bug Report: HTTP 500 when clicking on Hub to view public chatbots

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#238]
### 📜 Description

HTTP 500 when clicking on Hub to view public chatbots

### 👟 Reproduction steps

Go to Hub menu

### 👍 Expected behavior

No error

### 👎 Actual Behavior with Screenshots

NA

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 📃 Provide any additional context for the Bug.

![e1](https://github.com/user-attachments/assets/8095620a-4013-4097-8e7b-99a8f3d6f6bb)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kom-senapati** [comment]
Ok solve it then

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : Works fine after applying new db migrations
