### ISSUE TITLE
🚀 Feature: Want to add security

### ISSUE THREAD

**Issue by Dipanita45** [kom-senapati/bot-verse#239]
### 🔖 Feature description

Security of the website 

### 🎤 Why is this feature needed ?
To protect the website from the harms 

### ✌️ How do you aim to achieve this?

Security of the website so that one can misuse it . 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [yes ]I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR! 
Thank you!!

Please assign me the issue 
@kom-senapati

**Comment by kom-senapati** [comment]
Fill the template properly!

**Comment by Dipanita45** [comment]
Updated

**Comment by kom-senapati** [comment]
Still not complete

**Comment by Dipanita45** [comment]
Okay I am doing

**Comment by Dipanita45** [comment]
I have updated the template

**Comment by kom-senapati** [comment]
✌️ How do you aim to achieve this?
Security of the website so that one can misuse it .

I am not getting any proper plan here. Please explain

**Comment by Dipanita45** [comment]
Necessary security to protect the website against the harms and no-one can misuse by adding necessary security for this website

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by kom-senapati** [comment]
You are not properly replying me

**Comment by Dipanita45** [comment]
I will add necessary security for this website to protect against the harms
and no-one can misuse

**Comment by Dipanita45** [comment]
Please please assign me
