### ISSUE TITLE
Add Dark Mode Toggle with Visual Enhancements

### ISSUE THREAD

**Issue by Varsha-1605** [kom-senapati/bot-verse#24]
# Expected Updates:
1. Implement a toggle button for light/dark mode with localStorage support.
2. Update HTML/CSS for dual-theme support with minimal changes.
3. Add smooth CSS transitions for color changes.
4. Include background gradients and a sparkle effect for the toggle.
5. Adjust the background grid to light lines in dark mode.

**Comment by kom-senapati** [comment]
Ok you can do this but use tailwind css

**Comment by Varsha-1605** [comment]
@kom-senapati by mistake i merged my code from base.html for toggle button in your repo. So if you can revert it that would helpful for me in order to pull request.

**Comment by kom-senapati** [comment]
Which PR

**Comment by Varsha-1605** [comment]
@kom-senapati just checked base.html, accidentally it got committed to Updated files.
Please revert it to the previous code then only I'll be able to pull the request.

**Comment by kom-senapati** [comment]
You can do that yourself. Search about it in google. Maybe rebase and checkout useful commands

**Comment by Ayushjhawar8** [comment]
is this issue still open?

**Comment by kom-senapati** [comment]
no
