### ISSUE TITLE
🚀 Feature: A Command Panel to access features quick

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#242]
### 🔖 Feature description

A Command Pannel

### 🎤 Why is this feature needed ?

For quick access

### ✌️ How do you aim to achieve this?

Adding Combobox

### 🔄️ Additional Information
![image](https://github.com/user-attachments/assets/74053893-d7c0-4096-a5a6-c3701b6e96e2)
![image](https://github.com/user-attachments/assets/fc1c8c42-6a21-41dc-9bb5-348b5dad47e0)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
looks cool
