### ISSUE TITLE
🐛 Bug Report: HTTP 500 when clicking on send button of chatbot

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#245]
### 📜 Description

 HTTP 500 when clicking on send button of chatbot

### 👟 Reproduction steps

Go to chatbot -> Type any prompt -> Click on send

### 👍 Expected behavior

No error

### 👎 Actual Behavior with Screenshots

![c1](https://github.com/user-attachments/assets/28fbda23-1809-41e8-bcaf-9dc57e361031)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kom-senapati** [comment]
Ok fix it
