### ISSUE TITLE
🐛 Bug Report: UI, Backend Chatbots and Image separation

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#247]
### 📜 Description

- separate chatbots and images 
- add user images on profile page
- Searching bugs 
- delete chatbot native alert replace by modal
- other small bugs

### 👟 Reproduction steps

UX

### 👍 Expected behavior

Bug free website

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/682ba933-a6be-440c-add1-c62ef0f8aed8)
![image](https://github.com/user-attachments/assets/f489544d-33f9-43ed-9290-dd3cf89b0555)

MORE...

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kom-senapati** [comment]
Solve
