### ISSUE TITLE
Add Voice Interaction (Speech Recognition & Text-to-Speech)

### ISSUE THREAD

**Issue by Varsha-1605** [kom-senapati/bot-verse#25]
# Expected Updates:  
1. Implement speech recognition for user input (start/stop via button).
2. Add text-to-speech to read chatbot responses aloud.
3. Update UI with microphone and stop buttons.
4. Test functionality for both voice input and output.

**Comment by Varsha-1605** [comment]
I would love to work on it, so will you assign this task to me?

**Comment by kom-senapati** [comment]
@Varsha-1605 First submit PR for assigned issues then I will assign. Also if any other contributor want they also can contribute ...

**Comment by priyanshuverma-dev** [comment]
@kom-senapati In mean time.
Let me drive my hands on this issue

**Comment by kom-senapati** [comment]
Ok @priyanshuverma-dev go ahead
