### ISSUE TITLE
🚀 Feature: Improve Image Generation Management

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#250]
### 🔖 Feature description

- make a deliciated page to manage images generated by user delete, publish them.

### 🎤 Why is this feature needed ?

for managing images

### ✌️ How do you aim to achieve this?

adding new features

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok add them
