### ISSUE TITLE
🚀 Feature: Migrate Image Generation Page to a modal form

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#251]
### 🔖 Feature description

As Image Generation Page  don't has many components so we can make modal form for it as it can be easier to use and accessible.
And i will improve the look and feel of the image generation. We will keep Image Generation Page as legacy.

### 🎤 Why is this feature needed ?

 improve the look and feel of the image generation

### ✌️ How do you aim to achieve this?

Making a modal form

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok add the modal
