### ISSUE TITLE
🚀 Feature: Chatbot management page like images one

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#255]
### 🔖 Feature description

make a deliciated page to manage chatbots generated by user delete, publish them.

### 🎤 Why is this feature needed ?

for managing chatbots at one place

### ✌️ How do you aim to achieve this?

new page making

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Add asap
