### ISSUE TITLE
🚀 Feature: Analytics for Chatbot and Images on their pages

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#256]
### 🔖 Feature description

- add likes and report analytics for 
- chatbot
- images

### 🎤 Why is this feature needed ?

for better understanding of engagement

### ✌️ How do you aim to achieve this?

adding a total likes and reports count and ranking images and chatbots

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Yup this feature is needed
