### ISSUE TITLE
Transform create_chatbot.html into a Stunning, Interactive User Experience

### ISSUE THREAD

**Issue by Varsha-1605** [kom-senapati/bot-verse#26]
# Expected Updates:
1. Apply a gradient background for enhanced visual aesthetics.
2. Update form input fields with animated labels and modern styling.
3. Add hover effects and smooth transitions to buttons and form elements.
4. Include an idea generation button and visual spark animations for interaction.
5. Ensure the design is fully responsive and user-friendly.

**Comment by kom-senapati** [comment]
Share some design you want to do

**Comment by Varsha-1605** [comment]
ok to pull request?

**Comment by kom-senapati** [comment]
Ok
