### ISSUE TITLE
🚀 Feature: Add more export options like xml, json, html

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#262]
### 🔖 Feature description

Add more chat export options
- JSON
- HTML
- XML

### 🎤 Why is this feature needed ?

for multiple export options

### ✌️ How do you aim to achieve this?

Adding more options

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok add
