### ISSUE TITLE
🚀 Feature: ADD speech control for chat bots 

### ISSUE THREAD

**Issue by shubhagarwal1** [kom-senapati/bot-verse#265]
### 🔖 Feature description

this feature will help user to control the speech of the output weather they want their output as verbal or as text

### 🎤 Why is this feature needed ?

for better user exp.

### ✌️ How do you aim to achieve this?

will handel this on client side 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Any updates?

**Comment by kom-senapati** [comment]
If @shubhagarwal1 is not doing

**Comment by kom-senapati** [comment]
@priyanshuverma-dev you can add speech controls near Bot Name like play pause icons
I guess @shubhagarwal1 is not doing so you can do PR

**Comment by shubhagarwal1** [comment]
> @priyanshuverma-dev you can add speech controls near Bot Name like play pause icons I guess @shubhagarwal1 is not doing so you can do PR

Hey @kom-senapati i am sorry for the delay, please allow @priyanshuverma-dev to complete my both issue if he wanted to, i have no issues with that.
