### ISSUE TITLE
Transform update_chatbot.html into a Stunning, Interactive User Experience

### ISSUE THREAD

**Issue by Varsha-1605** [kom-senapati/bot-verse#27]
# Expected Updates:
1. Apply a gradient background for enhanced visual aesthetics.
2. Update form input fields with animated labels and modern styling.
3. Add hover effects and smooth transitions to buttons and form elements.
4. Include a back button with visual spark animations for interaction.
5. Ensure the design is fully responsive and user-friendly.

**Comment by kom-senapati** [comment]
Share design which you want to implement

**Comment by Varsha-1605** [comment]
I have designed something

![image](https://github.com/user-attachments/assets/1f3ab511-1637-4f13-ab20-196a72a1baa4)

**Comment by Varsha-1605** [comment]
ok to pull request?

**Comment by kom-senapati** [comment]
Ok assigning then

**Comment by Varsha-1605** [comment]
@kom-senapati 
I created the entire update_chatbot.html page from scratch, including forms, animations, and responsive design. Given the scope of the work, I believe it fits the Level 2 category rather than Level 1. Please update the label accordingly.
