### ISSUE TITLE
🚀 Feature: Implement Auto-Labeling Workflow for GitHub

### ISSUE THREAD

**Issue by aditiverma-21** [kom-senapati/bot-verse#273]
### 🔖 Feature description

This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests

### 🎤 Why is this feature needed ?

This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests 

### ✌️ How do you aim to achieve this?

git hub workflow features

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Not needed
