### ISSUE TITLE
🚀 Feature: Text to handwriting PDF Magic Tool

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#274]
### 🔖 Feature description

A magic tool to convert text to handwriting notes so that it can be printed

### 🎤 Why is this feature needed ?

for homework

### ✌️ How do you aim to achieve this?

using python

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
yeah can add
