### ISSUE TITLE
🚀 Feature: Adding a Workflow for greetings to new issue

### ISSUE THREAD

**Issue by aditiverma-21** [kom-senapati/bot-verse#275]
### 🔖 Feature description

This workflow runs whenever a new issue or pull request is opened.
Greet User: It uses the actions-ecosystem/action-create-comment action to post a customized comment directly on the issue or pull request.
Personalized Message: The message greets the user by username and dynamically adjusts based on whether it’s an issue or pull request. It also includes a link to the contribution guidelines for new contributors.

### 🎤 Why is this feature needed ?

Benefits of the Greeting Workflow

Improves User Experience
Encourages Quality Contributions
Reduces Common Questions

### ✌️ How do you aim to achieve this?

Github workflow

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Duplicate of #224
