### ISSUE TITLE
🚀 Feature: Add A Image Captioning Magic

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#279]
### 🔖 Feature description

- Add A Image Captioning Magic 

![image](https://github.com/user-attachments/assets/fca6e7e6-009a-4996-a0db-3fca74b9356d)

### 🎤 Why is this feature needed ?

Magic Tools

### ✌️ How do you aim to achieve this?

Using Pytorch and transformers

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok add it
