### ISSUE TITLE
🚀 Feature: QR Code Generator Magic Tool

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#280]
### 🔖 Feature description

- add a QR Code Generator Magic Tool

### 🎤 Why is this feature needed ?

for sharing easier

### ✌️ How do you aim to achieve this?

python

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
good one
