### ISSUE TITLE
🚀 Feature: Chatbot Page revamp

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#283]
### 🔖 Feature description

- revamp chatbot page with nice ui

### 🎤 Why is this feature needed ?

for more readability

### ✌️ How do you aim to achieve this?

tweaking UI

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok can do
