### ISSUE TITLE
🐛 Bug Report: Anonymous Chat UI, Navigation bug, UI consistency

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#289]
### 📜 Description

- Anonymous Chat UI
- Navigation bug
- UI consistency

### 👟 Reproduction steps

On Anonymous Chat UI

### 👍 Expected behavior

Chatbot page like

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/1e176bfb-0cbe-4a51-91b6-766f7b496f6f)

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kom-senapati** [comment]
Yup make all consistent
