### ISSUE TITLE
🚀 Feature: Terms and Condition Page 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#290]
### 🔖 Feature description

add a terms and condition page

### 🎤 Why is this feature needed ?

for better security

### ✌️ How do you aim to achieve this?

adding one

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Ok add it
