### ISSUE TITLE
🚀 Feature: Add a About page with contributors showcase

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#292]
### 🔖 Feature description

add a about page and contributors from GitHub

### 🎤 Why is this feature needed ?

for more authenticity

### ✌️ How do you aim to achieve this?

using GitHub API

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment]
Good idea

**Comment by kom-senapati** [comment]
Use framer motion if you can
