### ISSUE TITLE
🚀 Feature: CREATE CUSTOM ISSUE TEMPLATE

### ISSUE THREAD

**Issue by alo7lika** [kom-senapati/bot-verse#297]
### 🔖 Feature description

Creating a custom issue template for the project will streamline the process of issue reporting and tracking. This template includes specific fields that guide users to provide relevant details, making it easier for maintainers to understand, prioritize, and resolve issues effectively. This addition is expected to improve the overall quality of reported issues and enhance team productivity.

### 🎤 Why is this feature needed ?

Consistency: It ensures that all issues reported follow a uniform structure. This makes it easier for contributors and maintainers to understand and prioritize issues.

Clarity: A well-defined template helps users articulate their issues clearly, providing all necessary information upfront. This minimizes back-and-forth communication for clarification.

Efficiency: By guiding users through the reporting process, you can reduce the time spent on reviewing and responding to issues. This streamlines the workflow for both reporters and maintainers.

Prioritization: It helps assess the severity and urgency of issues based on the information provided in the template.

Documentation: Templates serve as documentation that can educate users about what is considered an acceptable issue report.

Encouragement: By making it easy to report issues, you encourage more contributions and engagement from the community.

### ✌️ How do you aim to achieve this?

![Screenshot 2024-10-28 234345](https://github.com/user-attachments/assets/d454610e-e577-446f-86c8-d4d6246d50ba)

### 🔄️ Additional Information

N/A

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alo7lika** [comment]
@kom-senapati assign me the task under "GSSOC-EXT"

**Comment by kom-senapati** [comment]
Issue templates are already there
