### ISSUE TITLE
Absence of Deployment Link 

### ISSUE THREAD

**Issue by Sameeratweb** [kom-senapati/bot-verse#3]
Adding a Deployment Link can be beneficial for contributors to projects under development, as it allows them to view it live.

I'd like to work on this. Please assign the issue to me and add relevant tags under the appropriate labels GSSoC'24-Extd.

**Comment by kom-senapati** [comment]
Where do you want to deploy it?

**Comment by kom-senapati** [comment]
For now I dont want to deploy it, we can have a demo video and screenshots in readme if you want can do that and attach.

**Comment by Sameeratweb** [comment]
any free services like github pages ,vercel,netlify etc.
