### ISSUE TITLE
Unavailability of Homepage Return Navigation, Some icons styling issues

### ISSUE THREAD

**Issue by PYIArun** [kom-senapati/bot-verse#4]
I explored the project, and it's really nice! I would like to offer some recommendations for changes:

1. When redirecting to the signup/login page, the "Return Back" button should work as intended. Currently, clicking it just toggles between the login and signup pages.  
 ![image](https://github.com/user-attachments/assets/eb4d3a8e-15c5-4ade-848c-37b9eb87c04c)

2. In the chatbot hub, the chat icon style has some positioning issues.  
   ![image](https://github.com/user-attachments/assets/4fd9f2a7-02f4-418a-ad91-d764be21f65a)

3. On the homepage, there is a "Dashboard" button when the user is logged in. However, while inside the dashboard, there should also be a way to navigate back to the homepage for exploration purposes. This would prevent users from feeling stuck and having to manually use the URL bar. Adding a "Home" option in the navigation alongside "Hub" and "Profiles" would improve usability.

If you would like to have any or all of these changes, kindly assign me under GSSOC. I am eager to contribute!

**Comment by kom-senapati** [comment]
Dashboard is home page only for all guys. Landing page is just for showcase purpose. So leave 3rd point and solve other 2 points.
