### ISSUE TITLE
Contributor list not updating

### ISSUE THREAD

**Issue by Ayushjhawar8** [kom-senapati/bot-verse#45]
i just checked the contributor list on readme, its not updating my profile in it 

![image](https://github.com/user-attachments/assets/42a8ad4f-9d62-48d5-af50-c9f16d3cd1b5)
![image](https://github.com/user-attachments/assets/fa692b1c-32d5-4834-b6b7-88867aab599b)

**Comment by Ayushjhawar8** [comment]
![image](https://github.com/user-attachments/assets/feb4fa76-4473-4989-83df-c1c78054cdb3)

**Comment by kom-senapati** [comment]
add github action to update

**Comment by Ayushjhawar8** [comment]
assign me i will try
