### ISSUE TITLE
Feat: Add performance boost with SPA

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#48]
- Currently website reloads every time when URL changes
- Implement feature like `react` with using only python and javascript
- Convert website into SPA-like web app.

**Demo**

  

https://github.com/user-attachments/assets/e21b1af6-9fcf-4e41-802a-80e6126c4cc8

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this feature.

**Comment by kom-senapati** [comment]
Yes go ahead
