### ISSUE TITLE
Enhancing a Flask Chatbot Application: Security Aspect - routes.py

### ISSUE THREAD

**Issue by Deeptig9138** [kom-senapati/bot-verse#5]
Making sure it is not vulnerable to attacks

Done as you asked @kom-senapati 
Please give hacktoberfest label too

**Comment by kom-senapati** [comment]
Ok start working 😄

**Comment by Shalinis19137** [comment]
i want to make Flask chatbot  more easier to use as high security maintained as requirements . Can you Assign this task to me.

**Comment by kom-senapati** [comment]
> i want to make Flask chatbot more easier to use as high security maintained as requirements . Can you Assign this task to me.

Its already assigned. Find another issue and raise it

**Comment by Ayesha480** [comment]
Can you assign me any task I want to work on it

**Comment by kom-senapati** [comment]
go ahead

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this issue.
I will fix some points:
- Remove and secure `API` routes
- Optimize data fetching and improve static data.
- Code refactor.

**Comment by kom-senapati** [comment]
Ok solve it
