### ISSUE TITLE
Add User Profile and Avatar Feature

### ISSUE THREAD

**Issue by SatyaD012** [kom-senapati/bot-verse#53]
Enhance the user experience by allowing users to create and manage personal profiles. This includes adding profile pictures (avatars) and a short bio.

Key Tasks:
User Profile Page:

Create a dedicated page where users can view and edit their personal information (e.g., display name, email, short bio).
Allow users to upload and update their profile picture (avatar).
Backend Changes:

Update the user model in the database to store new fields:
Avatar URL
Short bio (text)
Add routes and functionality to handle profile updates.
Frontend Changes:

Create a profile page UI using Tailwind CSS that displays user details and allows edits.
Implement form validation for bio input (e.g., character limit, HTML sanitization).
Dark/Light Mode Support:

Ensure the profile page supports both light and dark themes. 
Hello @kom-senapati ,pls assign the issue to me

**Comment by priyanshuverma-dev** [comment]
My I work on this issue 
@kom-senapati

**Comment by kom-senapati** [comment]
Go ahead @priyanshuverma-dev

**Comment by priyanshuverma-dev** [comment]
@kom-senapati 
Let me add Avatar for bots also

**Comment by kom-senapati** [comment]
yes, dont do any manual use api only
