### ISSUE TITLE
[Feat]: Include tailwind autocomplete and stable styling config with dark mode

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#55]
- Generate static styles with tailwind remove `CDN` usage.
- Add stable config logic and dark mode
- Add a theme toggle switch

**Comment by priyanshuverma-dev** [comment]
@kom-senapati I have proposed a fix on this issue.
Please let me know if it works

**Comment by kom-senapati** [comment]
Yup go ahead
