### ISSUE TITLE
[FIX] Redesign whole website and fix broken ui and theme

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#57]
- Full website redesign every page
- Both light and dark theme included
- Fix broken theme and UI
- Make a consistent UI/UX

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I work on this issue.
It needs for website UI design with both dark and light theme

**Comment by kom-senapati** [comment]
Ok go ahead. Focus on consistency
