### ISSUE TITLE
Enhancement: adding tests

### ISSUE THREAD

**Issue by htanmo** [kom-senapati/bot-verse#59]
Adding few tests for the application.

**Comment by htanmo** [comment]
@kom-senapati Please assign me this issue.

**Comment by kom-senapati** [comment]
Tests for which part ?

**Comment by htanmo** [comment]
For the different routes using pytest-flask

**Comment by htanmo** [comment]
But I think for doing so I need to change the structure of the project a little bit, so that I can create a new tests directory containing the tests separately while transferring the business logic of the application in a package that way I can import the functions and variables from different files from that package to be imported to be used in tests.

**Comment by htanmo** [comment]
I can open a new issue for the restructure then do the tests after if you need.

**Comment by kom-senapati** [comment]
Ok then raise issue for restructure
