### ISSUE TITLE
[feat] : Adding features to bot-verse/routes.py

### ISSUE THREAD

**Issue by Yash-Vashishth** [kom-senapati/bot-verse#66]
Hi @kom-senapati!! Here is a list of improvements  I want to make in the file to improve functionality, readability and speed of routes:-

1.Blueprints: Introduced Flask Blueprints for better route organization.
2.Docstrings: Added docstrings to all route functions.
3.Error Handling: Improved error handling with try-except blocks for database operations.
4.Security: Ensured user inputs are validated and sanitized.
5.Performance: Used eager loading for database queries where applicable.
6.Code Consistency: Ensured consistent use of quotes and formatting throughout the file.

Please assign me this issue.
Thanks,
Yash Vashishth
(Contributor, GSSoC'24(Extd) and Hacktoberfest)

**Comment by Yash-Vashishth** [comment]
Also pls add the gssox-ext and hacktoberfest and level 2 tag to the issue

**Comment by kom-senapati** [comment]
Ok go ahead

**Comment by PrathamChitkara** [comment]
Hi @kom-senapati can you assign me this issue please

**Comment by kom-senapati** [comment]
Its assigned already

**Comment by Yash-Vashishth** [comment]
Hi @PrathamChitkara and @kom-senapati im working on this issue. Will raise pr in half an hour
