### ISSUE TITLE
Error Occured while Installation

### ISSUE THREAD

**Issue by PYIArun** [kom-senapati/bot-verse#70]
### Issue: Error During `flask db init`

I encountered an error when running the command:
```bash
flask db init
```

![Error Image](https://github.com/user-attachments/assets/371a29a7-41b3-451c-9848-7cfe1249fb00)

This issue has affected subsequent migration commands as well.

**Comment by kom-senapati** [comment]
Change "name" to 'name'

**Comment by kom-senapati** [comment]
You can raise an issue for it

**Comment by PYIArun** [comment]
> You can raise an issue for it

I have already raised this issue as #70.

**Comment by PYIArun** [comment]
You meant PR Request for this corresponding issue? @kom-senapati

**Comment by kom-senapati** [comment]
Ok assigning
