### ISSUE TITLE
[Feature]: A anonymous chat bot that don't save messages 

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#78]
- A anonymous chatting bot which can be used to generate prompt or for temporary chat
- include new API route.

**Comment by priyanshuverma-dev** [comment]
@kom-senapati May I Integrate this issue.
It needs to make new API 
- endpoint, 
- UI
- JS functions

**Comment by kom-senapati** [comment]
Ok you can. Also add it for not logged in users of around 5 chats limit
