### ISSUE TITLE
Enhancing the home page to make it easily useable

### ISSUE THREAD

**Issue by Jay-1409** [kom-senapati/bot-verse#88]
<img width="949" alt="image" src="https://github.com/user-attachments/assets/a4c73cd9-abab-4143-b6d0-d841617a4868">
The above is the current home page, which is very simple, so I would like to add some information to it. 
Such as : 
- Background:
- Introduction
- Chat Window:
- Typography
- Button Styling:
- Message Bubbles:
- Navbar or Header:

I would like to work under gssoc extd 2024 and hacktoberfest 2024

**Comment by kom-senapati** [comment]
Nope, it's working fine. All those things are available.
