### ISSUE TITLE
Add Back to top Button

### ISSUE THREAD

**Issue by sambedan1** [kom-senapati/bot-verse#89]
Back to top button Improved User Experience: It allows users to easily navigate back to the top of the page, especially on long-scroll pages.

**Comment by kom-senapati** [comment]
Ok you can add it

**Comment by RishabxBhardwaj** [comment]
can i do this

**Comment by kom-senapati** [comment]
If @sambedan1 dont want to do @RishabxBhardwaj can do

**Comment by ishaa05** [comment]
Can I please try fixing this?

**Comment by kom-senapati** [comment]
@sambedan1 Are you working

**Comment by sambedan1** [comment]
yes

**Comment by kom-senapati** [comment]
Any updates @sambedan1

**Comment by kom-senapati** [comment]
Unassigning as you didnt reply!

**Comment by RishabxBhardwaj** [comment]
assign it to me

**Comment by priyanshuverma-dev** [comment]
@kom-senapati  assign this issue to me. Will add in client app

**Comment by kom-senapati** [comment]
You both try
@RishabxBhardwaj try on html files
@priyanshuverma-dev try on client app
