### ISSUE TITLE
add dark and light toggle mode 

### ISSUE THREAD

**Issue by sv410** [kom-senapati/bot-verse#91]
You
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Screenshots**

**screenshots/video of feature**

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines
Copilot
Feature Request: Light and Dark Mode Toggle
Is your feature request related to a problem? Please describe. I'm always frustrated when browsing websites without the option to switch between light and dark modes. This limitation can lead to eye strain, especially in different lighting environments, reducing the overall user experience.

Describe the solution you'd like I propose adding a toggle button that allows users to switch between light and dark modes. This feature will enhance usability by providing flexibility, improving readability, and reducing eye strain.

Screenshots If applicable, add screenshots to help explain your problem.

Screenshots/Video of Feature Add any other context or screenshots about the feature request here.

Check List

[x ] I am contributing under GSSoC-ext
![WhatsApp Image 2024-10-13 at 1 57 25 PM](https://github.com/user-attachments/assets/598b55f2-8405-4581-9fb2-2e816667f9bc)

[ x] I am contributing under hacktoberfest

[ x] I follow contribution guidelines

Feel free to assign this issue to me, as I would like to contribute to its development. 
![WhatsApp Image 2024-10-13 at 1 57 57 PM](https://github.com/user-attachments/assets/8d988d0b-2ad0-40f5-8278-a1741d8ffb95)

**Comment by kom-senapati** [comment]
Ok add it

**Comment by sv410** [comment]
pls add level 3 if u liked my work!

**Comment by kom-senapati** [comment]
A single toggle cant be level 3. Raise more issues.

**Comment by kom-senapati** [comment]
Do a single PR in this repo not your fork @sv410

**Comment by kom-senapati** [comment]
@sv410 Any updates ??

**Comment by sv410** [comment]
@kom-senapati will update it soon.

**Comment by Manojkumar2806** [comment]
If it possible, @kom-senapati can you assign for me. I create it with in one hour. If it possible only,

**Comment by kom-senapati** [comment]
I can but it looks like @sv410 is working

**Comment by kom-senapati** [comment]
@sv410 Why are you doing multiple PRs? Do a single PR with all changes required, and fill the template properly. Also, add video or ss of after/before changes.

**Comment by sv410** [comment]
@Manojkumar2806 need help!

**Comment by Manojkumar2806** [comment]
Yes sir assign to me i solve this. could you please provide gssoc and hacktoberfest tag.

**Comment by kom-senapati** [comment]
Ok @Manojkumar2806

**Comment by Manojkumar2806** [comment]
Hello Sir, if there are any necessary changes, please inform me so that I can resolve them.
