### ISSUE TITLE
text alignment issue on small screen

### ISSUE THREAD

**Issue by parteekxo** [kom-senapati/bot-verse#94]
hey there is text alignment issue on small screens.
![image](https://github.com/user-attachments/assets/56be10c3-b49c-4884-81ba-86e570367ff8)
I can solve this problem by changing the styling of the text.
please assign me under hacktoberfest and gssoc-ext

**Comment by kom-senapati** [comment]
Ok solve

**Comment by parteekxo** [comment]
@kom-senapati issue has been fixed, waiting for the approval. :)
