### ISSUE TITLE
feat: Dropdown menu on small devices

### ISSUE THREAD

**Issue by parteekxo** [kom-senapati/bot-verse#96]
![image](https://github.com/user-attachments/assets/ba97432a-300e-4685-8d8e-2ba7f599545d)
the Login and Sign up should collapse into a dropdown menu on small screens this will also prevent the logo to move onto next line.
Please assign me under hacktoberfest and gssoc-ext.
Thank You!

**Comment by kom-senapati** [comment]
Ok you can do this

**Comment by kom-senapati** [comment]
Any updates

**Comment by parteekxo** [comment]
working on it, i was having issues implementing in tailwind.

**Comment by kom-senapati** [comment]
Ok good

**Comment by parteekxo** [comment]
> Ok good

Done :saluting_face:
