### ISSUE TITLE
Update README for Enhanced of Contributor Section

### ISSUE THREAD

**Issue by AnushkaChouhan25** [kom-senapati/bot-verse#97]
Propose to enhance the README file by making it more engaging. Additionally, include a contributor section similar to the one in the provided image to acknowledge the contributors effectively.

![image](https://github.com/user-attachments/assets/6b6394b9-a2d0-4526-ad9a-ac2c33efe46b)

**Comment by kom-senapati** [comment]
Auto updates ?

**Comment by AnushkaChouhan25** [comment]
> Auto updates ?

Yes

**Comment by kom-senapati** [comment]
Ok then add that

**Comment by AnushkaChouhan25** [comment]
> Ok then add that

Done
