### ISSUE TITLE
[BUG] Sign up is not working as expected

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#98]
- sign up form is giving error 
![image](https://github.com/user-attachments/assets/49ca1306-99a5-44e5-9509-84fe30676235)

**Comment by priyanshuverma-dev** [comment]
@kom-senapati Please assign this issue to me

**Comment by parteekxo** [comment]
> @kom-senapati Please assign this issue to me

the issue is solved waiting to be merged

**Comment by priyanshuverma-dev** [comment]
@parteekxo Thanks for updating
